# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vb_08B5R5bBeOvG_MzBePbDOG3siMQVU

**Appending** *dataframes*:
"""

import pandas as pd
data1=pd.read_csv("/content/time_series_covid19_confirmed_global (1).csv")
data2=pd.read_csv("/content/time_series_covid19_confirmed_global.csv")
print(data1)

data2

data3=data1.append(data2)  #data2 will be updated right below data1 with the same indexes without reseting the indexes
print(data3)

data3.loc[0]   #giving both zero index rows

data3.reset_index(drop=True)

data4=pd.read_csv("/content/vgsalesGlobale.csv")
print(data4)

data5=data3.append(data4)
print(data5)  #those values which are not in data3 or data4 are replaced by NaN

