# -*- coding: utf-8 -*-
"""CSV and Pandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YDS1fm3yvpDU8UodKf843j0x-_Jr2jY6
"""

import pandas as pd
pd.DataFrame({'Name':['Ahmed','Khubaib',"Ali"],'Age':[19,21,23]})
pd.Series([1,2,3,4,5])
sales=pd.Series([1,2,3], index=['One','Two','Three'], name='Product A')
print(sales)
sales.to_frame()     #giving a format to our series and convert into a dataframe

data=pd.read_csv('/time_series_covid19_confirmed_global (1).csv')
print(data)
#print the shape of the file
print("The shape is:",data.shape)

#print the head of the file which is first five rows
print("---The head is here:---\n",data.head())

#information, which can be used to further manipulate the data
print(data.info())

print(data.describe())

Pakistan = data[data['Country/Region']=='Pakistan']
print(Pakistan.shape)
print(Pakistan)
print(Pakistan.columns[1])
print(Pakistan.iloc[0][3])
for i in range(4,865):
  if Pakistan.iloc[0][i]>0:
    break
print("Pakistan's First Covid-19 case was on:", Pakistan.columns[i])

#perentage of pakistanis suffered from covid-19:
print(((Pakistan.iloc[0][864])/220000000)*100)

uk=data[data['Country/Region']=='United Kingdom']
lst=[]
lst1 = []
for i in range(14):
  lst.append(uk.iloc[i][0])
#now find the greatest num first make a list of cases
for i in range(14):
  lst1.append(uk.iloc[i][864])
for i in range(len(lst1)):
  if lst1[i] == max(lst1):
    print("The state which have the greatest cases is:", uk.iloc[13][0])

